kubeconfig: !ENV "${HOME}/kubeconfig"
output_log_file: /tmp/openshift-day2-configuration.log

configurators:
    ldap:
        bind_dn: <name>
        bind_password: <password>
        idp_name: ldap
    ingress:
        domain: <ocp.customer.domain.com>
